### ISSUE TITLE
cannot import name 'reinforced_cross_entropy'

### ISSUE THREAD

**Issue by ouic** [piteren/pypoks#12]
ImportError: cannot import name 'reinforced_cross_entropy' from 'torchness.base_elements'

I'm having this message when trying to run `python run/run_human_game.py`

just replacing `reinforced_cross_entropy` by `scaled_cross_entropy` seems to solve the problem

**Comment by piteren** [comment]
Hi,
yes, it was a problem witch changed dependency code.
Already fixed this, please checkout from master.
