### ISSUE TITLE
Error with run_train_loop.py

### ISSUE THREAD

**Issue by phanbin777** [piteren/pypoks#13]
Hi,
I have an error with "run_train_loop.py"
Looking forward to your support. Thank you very much

![image](https://github.com/piteren/pypoks/assets/25605681/47b587d3-5d5a-4794-8f56-0fa3c39e3669)

**Comment by piteren** [comment]
Hi,
this script has been depreciated (and not fixed), now is deleted,
so please checkout, update dependencies (especially pypaq, torchness),
and use the scripts from run dir. Should work.
